# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Code Review

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  css:
    name: Check CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Checks
        run: npm run lint:style
  js:
    name: Check JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Checks
        run: npm run lint:js
  php:
    name: Check PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
          coverage: none
      - name: Install Dependencies
        uses: ramsey/composer-install@v2
        env:
          COMPOSER_AUTH: ${{ secrets.PLATFORM_COMPOSER_AUTH }}
      - name: Run Checks
        run: composer run-script lint
